#define KW_INT 1
#define KW_VOID 2
#define KW_RETURN 3
#define KW_CONST 4
#define KW_MAIN 5
#define OP_ADD 6//+
#define OP_SUB 7//-
#define OP_MUL 8//*
#define OP_DIV 9///
#define OP_MOD 10//%
#define OP_EONE 11//=
#define OP_GREATER 12//>
#define OP_LESS 13//<
#define OP_ETWO 14//==
#define OP_LOE 15//<=
#define OP_GOE 16//>=
#define OP_NE 17//!=
#define OP_AND 18//&&
#define OP_OR 19//||
#define SE_LB 20//(
#define SE_RB 21//)
#define SE_LBRACE 22//{
#define SE_RBRACE 23//}
#define SE_SEM 24//;
#define SE_COM 25//,

#define KW 101
#define OP 102
#define SE 103
#define IDN 104
#define INT 105